apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  labels:
    app: deployment-frontend
spec:
  selector:
    matchLabels:
      app: deployment-frontend
  template:
    metadata:
      labels:
        app: deployment-frontend
    spec:
      containers:
      - name: simple-fortune-cookie-frontend
        image: diblo/simple-fortune-cookie-frontend:latest
        ports: 
        - containerPort: 8080